// AVC Decoder Phase-1 motion-prediction pipeline top.
// This wrapper closes the real Candidate block into the verified backend;
// the spatial MVP and capture pulse are observations, not external inputs.
module vc_mvp_dec_top #(
    parameter VC_CTU_X_NB  = 7,
    parameter VC_CTU_Y_NB  = 7,
    parameter VC_CU_X_NB   = 9,
    parameter VC_CU_Y_NB   = 9,
    parameter NUM_REF      = 2,
    parameter VC_EN_BI_DIR = 0,
    parameter VC_PIC_X_NB  = 12,
    parameter VC_PIC_Y_NB  = 12,
    parameter MRG2MC_DW    = VC_PIC_X_NB + VC_PIC_Y_NB + 39
) (
    input                           clk_vc,
    input                           vc_rst_z,
    input                           codec_mode,
    input                           reg_slice_go,

    input                           ccu2irpu_valid,
    output                          irpu2ccu_rdy,
    input      [1:0][15:0]          ccu2irpu_mvd,
    input      [3:0]                ccu2irpu_ref_idx,
    input                           ccu2irpu_is_skip,
    input                           ccu2irpu_part_mode,
    input      [1:0]                ccu2irpu_sub_idx,
    input      [2:0]                dec_txn_cux,
    input      [2:0]                dec_txn_cuy,
    input      [1:0]                dec_txn_a_avail,
    input      [2:0]                dec_txn_b_avail,
    input      [VC_CTU_X_NB-1:0]    dec_txn_ctux,
    input      [VC_CTU_Y_NB-1:0]    dec_txn_ctuy,
    input      [VC_CTU_X_NB-1:0]    reg_pic_width_ctu_m1,

    // Real Neighbor SRAM/Col/RefList interfaces are preserved from backend.
    output     [4:0]                irpu2neib_b_req,
    output     [4:0]                irpu2neib_b_addr,
    input                           neib_b2irpu_gnt,
    input                           neib_b2irpu_rd_lat,
    input      [67:0]               neib_b2irpu_rd,
    output     [1:0]                irpu2neib_a_req,
    output     [1:0]                irpu2neib_a_addr,
    input                           neib_a2irpu_gnt,
    input                           neib_a2irpu_rd_lat,
    input      [67:0]               neib_a2irpu_rd,
    output                          irpu2col_req,
    output     [4:0]                irpu2col_addr,
    input                           col2irpu_gnt,
    input                           col2irpu_rd_lat,
    input      [83:0]               col2irpu_rd,
    output                          irpu2ref_req,
    output     [3+VC_EN_BI_DIR:0]   irpu2ref_addr,
    input                           ref2irpu_gnt,
    input                           ref2irpu_rd_lat,
    input      [32:0]               ref2irpu_rd,

    input      [2:0]                mc2mrg_cand_ack,
    output     [2:0]                dec_mrg2mc_cand_rdy,
    output     [2:0][MRG2MC_DW-1:0] dec_mrg2mc_cand_data,
    output     [2:0]                dec_mrg2mc_cand_nb,
    output     [2:0]                dec_mrg2mc_cand_done,

    // Pipeline and Candidate observations for integration verification.
    output                          dec_neib_start,
    output                          dec_cand_start,
    output                          cand_capture_done,
    output                          cand_busy,
    output     [31:0]               dec_spatial_mvp,
    output                          dec_recon_start,
    output                          recon_done,
    output                          dec_send,
    output                          mc_commit,
    output     [31:0]               dec_final_mv,
    output     [3:0]                dec_final_ref_idx,
    output     [1:0][15:0]          dec_mvd,
    output     [3:0]                dec_ref_idx,
    output                          dec_is_skip,
    output                          dec_part_mode,
    output     [1:0]                dec_sub_idx,
    output     [2:0]                dec_cux,
    output     [2:0]                dec_cuy,
    output     [VC_CTU_X_NB-1:0]    dec_ctux,
    output     [VC_CTU_Y_NB-1:0]    dec_ctuy,
    output                          dec_is_pic_top16,
    output                          dec_is_pic_left16,
    output     [16:0]               dec_selected_cu_cmd,
    output     [1:0][33:0]          amvp_neib_a,
    output     [2:0][33:0]          amvp_neib_b,
    output     [1:0]                dec_a_avail,
    output     [2:0]                dec_b_avail,
    output     [1:0]                dec_expected_sub_idx,
    output                          dec_busy,
    output     [5:0]                dbg_dec_fsm_cs,
    output                          raw_neib_done_amvp,
    output                          neib_done_amvp
);

    vc_mvp_dec_backend_top #(
        .VC_CTU_X_NB  (VC_CTU_X_NB),
        .VC_CTU_Y_NB  (VC_CTU_Y_NB),
        .VC_CU_X_NB   (VC_CU_X_NB),
        .VC_CU_Y_NB   (VC_CU_Y_NB),
        .NUM_REF      (NUM_REF),
        .VC_EN_BI_DIR (VC_EN_BI_DIR),
        .VC_PIC_X_NB  (VC_PIC_X_NB),
        .VC_PIC_Y_NB  (VC_PIC_Y_NB),
        .MRG2MC_DW    (MRG2MC_DW)
    ) U_BACKEND (
        .clk_vc                  (clk_vc),
        .vc_rst_z                (vc_rst_z),
        .codec_mode              (codec_mode),
        .reg_slice_go            (reg_slice_go),
        .ccu2irpu_valid          (ccu2irpu_valid),
        .irpu2ccu_rdy            (irpu2ccu_rdy),
        .ccu2irpu_mvd            (ccu2irpu_mvd),
        .ccu2irpu_ref_idx        (ccu2irpu_ref_idx),
        .ccu2irpu_is_skip        (ccu2irpu_is_skip),
        .ccu2irpu_part_mode      (ccu2irpu_part_mode),
        .ccu2irpu_sub_idx        (ccu2irpu_sub_idx),
        .dec_txn_cux             (dec_txn_cux),
        .dec_txn_cuy             (dec_txn_cuy),
        .dec_txn_a_avail         (dec_txn_a_avail),
        .dec_txn_b_avail         (dec_txn_b_avail),
        .dec_txn_ctux            (dec_txn_ctux),
        .dec_txn_ctuy            (dec_txn_ctuy),
        .reg_pic_width_ctu_m1    (reg_pic_width_ctu_m1),
        .cand_capture_done       (cand_capture_done),
        .dec_spatial_mvp         (dec_spatial_mvp),
        .dec_cand_start          (dec_cand_start),
        .dec_selected_cu_cmd     (dec_selected_cu_cmd),
        .amvp_neib_a             (amvp_neib_a),
        .amvp_neib_b             (amvp_neib_b),
        .irpu2neib_b_req         (irpu2neib_b_req),
        .irpu2neib_b_addr        (irpu2neib_b_addr),
        .neib_b2irpu_gnt         (neib_b2irpu_gnt),
        .neib_b2irpu_rd_lat      (neib_b2irpu_rd_lat),
        .neib_b2irpu_rd          (neib_b2irpu_rd),
        .irpu2neib_a_req         (irpu2neib_a_req),
        .irpu2neib_a_addr        (irpu2neib_a_addr),
        .neib_a2irpu_gnt         (neib_a2irpu_gnt),
        .neib_a2irpu_rd_lat      (neib_a2irpu_rd_lat),
        .neib_a2irpu_rd          (neib_a2irpu_rd),
        .irpu2col_req            (irpu2col_req),
        .irpu2col_addr           (irpu2col_addr),
        .col2irpu_gnt            (col2irpu_gnt),
        .col2irpu_rd_lat         (col2irpu_rd_lat),
        .col2irpu_rd             (col2irpu_rd),
        .irpu2ref_req            (irpu2ref_req),
        .irpu2ref_addr           (irpu2ref_addr),
        .ref2irpu_gnt            (ref2irpu_gnt),
        .ref2irpu_rd_lat         (ref2irpu_rd_lat),
        .ref2irpu_rd             (ref2irpu_rd),
        .mc2mrg_cand_ack         (mc2mrg_cand_ack),
        .dec_mrg2mc_cand_rdy     (dec_mrg2mc_cand_rdy),
        .dec_mrg2mc_cand_data    (dec_mrg2mc_cand_data),
        .dec_mrg2mc_cand_nb      (dec_mrg2mc_cand_nb),
        .dec_mrg2mc_cand_done    (dec_mrg2mc_cand_done),
        .dec_neib_start          (dec_neib_start),
        .dec_recon_start         (dec_recon_start),
        .recon_done              (recon_done),
        .dec_send                (dec_send),
        .mc_commit               (mc_commit),
        .dec_final_mv            (dec_final_mv),
        .dec_final_ref_idx       (dec_final_ref_idx),
        .dec_mvd                 (dec_mvd),
        .dec_ref_idx             (dec_ref_idx),
        .dec_is_skip             (dec_is_skip),
        .dec_part_mode           (dec_part_mode),
        .dec_sub_idx             (dec_sub_idx),
        .dec_cux                 (dec_cux),
        .dec_cuy                 (dec_cuy),
        .dec_ctux                (dec_ctux),
        .dec_ctuy                (dec_ctuy),
        .dec_is_pic_top16        (dec_is_pic_top16),
        .dec_is_pic_left16       (dec_is_pic_left16),
        .dec_a_avail             (dec_a_avail),
        .dec_b_avail             (dec_b_avail),
        .dec_expected_sub_idx    (dec_expected_sub_idx),
        .dec_busy                (dec_busy),
        .dbg_dec_fsm_cs          (dbg_dec_fsm_cs),
        .raw_neib_done_amvp      (raw_neib_done_amvp),
        .neib_done_amvp          (neib_done_amvp)
    );

    vc_mvp_dec_cand U_CANDIDATE (
        .clk_vc           (clk_vc),
        .vc_rst_z         (vc_rst_z),
        .reg_slice_go     (reg_slice_go),
        .dec_cand_start   (dec_cand_start),
        .selected_cu_cmd  (dec_selected_cu_cmd),
        .amvp_neib_b      (amvp_neib_b),
        .amvp_neib_a      (amvp_neib_a),
        .dec_spatial_mvp  (dec_spatial_mvp),
        .cand_capture_done(cand_capture_done),
        .cand_busy        (cand_busy)
    );

endmodule
